#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.56.10/crudboy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root